### ISSUE TITLE
Why does the user not receive the email + password option?

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#1]
**Specifications**
1. MacOS Chrome

**Problem**

1. User has previously signed up with email and password combination but when the user clicks on Join Topic after receiving a topic invitation to their email and is prompted to login, they get only these two options (screenshot attached)

<img width="1438" alt="Screenshot 2023-02-20 at 23 12 38" src="https://user-images.githubusercontent.com/72747107/220199778-de38aedc-02bd-486a-b500-390ed5696c51.png">

**Expected result**

1. User should always be able to login with user and password combination 
2. Instead of "bad request" user should receive detailed information about how to correct the course of action (for example "please select an option to proceed").

**Comment by ilmartyrk** [comment]
@ssin1901 this screenshot is from our live environment, though I've taken notice and will fix this in there
