### ISSUE TITLE
Attachment One Drive option doesn't do anything 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#11]
**Specifications**

MacOS Chrome

**Problem**

When the user clicks on add attachment and clicks on the One Drive option, nothing happens. All other options display a pop up window (screenshot attached)

<img width="1251" alt="Screenshot 2023-02-22 at 19 57 10" src="https://user-images.githubusercontent.com/72747107/220715075-4d6145e5-71c4-412a-8527-33e315b64080.png">

**Expected result**
One Drive window should open

**Comment by ilmartyrk** [comment]
@ssin1901 fixed
