### ISSUE TITLE
Random delete button for Invite & Share Public Group 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#17]
**Specifications**

MacOS Safari

**Problem**

When the user clicks on Invite & Share from a Public group topic and presses enter, there is a random delete button (screenshot attached).

<img width="1255" alt="Screenshot 2023-02-28 at 00 08 33" src="https://user-images.githubusercontent.com/72747107/221697379-c0bf5d45-9081-4b9a-a39e-756cec8b3e6c.png">

**Expected result**
Only one delete button located to the right of emails.

**Comment by ilmartyrk** [comment]
@ssin1901 this is actually delete all button, when user has admin level then they will have dropdown there too. I've fixed the styling issues but will not change anything else as it will change with UX/UI update
