### ISSUE TITLE
Test app does not load on MacOS Safari

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#2]
**Specifications**

MacOS Chrome

**Problem**

test.app.citizenos.com does not load on MacOS Safari (screenshot attached). Safari developer tools show this error (screenshot attached)
<img width="1372" alt="Screenshot 2023-02-21 at 20 56 12" src="https://user-images.githubusercontent.com/72747107/220437318-e5d9b392-1705-42ac-ab5c-3c194d7b82d1.png">
<img width="1375" alt="Screenshot 2023-02-21 at 20 57 27" src="https://user-images.githubusercontent.com/72747107/220437335-5864c866-85b5-4b83-9065-263fb203162b.png">

**Expected result**
Page should load (works alright on Chrome)

**Comment by ilmartyrk** [comment]
Found a possible explanation, will try to fix this https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by ilmartyrk** [comment]
@ssin1901 the issue was related to the link that I previously posted about, I commented out that part of the code (its not anything too important), and it started working on safari. I will keep this issue open until i've found a proper solution for this
