### ISSUE TITLE
Unable to search accounts despite show my profile in search results > On

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#32]
**Specifications**
MacOS Safari and Google Chrome

**Problem**
Even when the user has set their settings to show profile in search results>On (screenshot 1, screenshot 2), the users name does not display in the search results (screenshot 3)
<img width="1198" alt="Screenshot 2023-03-15 at 21 05 14" src="https://user-images.githubusercontent.com/72747107/225417570-5ea4c60d-8f80-407f-b6d4-d4e57fe6926c.png">
<img width="1199" alt="Screenshot 2023-03-15 at 21 09 58" src="https://user-images.githubusercontent.com/72747107/225417590-3363cb50-aaf7-4548-853d-b884185fe316.png">
<img width="1213" alt="Screenshot 2023-03-15 at 21 05 04" src="https://user-images.githubusercontent.com/72747107/225417719-6d68a417-8010-4e77-ab61-496edf6f523e.png">

**Expected result**
Users name should be displayed

**Comment by ilmartyrk** [comment]
@ssin1901 it actually works, but the minimum required character limit is set to 5 to start the search

**Comment by anettlinno** [comment]
Triage 83. Minimum character limit is helping to avoid the situations where people would spy who are users in COS platform. Therefore people who invite other Users should know who they are inviting anyway (either their email or username). 
Closing this issue with no further action.
