### ISSUE TITLE
KOU button form fields out of alignment and a href in plaintext  

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#4]
**Specifications**

MacOS Chrome

**Problem**
The KOU button has several form fields that are out of alignment and <a href> in plain text (screenshot attached)

<img width="1434" alt="Screenshot 2023-02-22 at 00 04 02" src="https://user-images.githubusercontent.com/72747107/220469983-b27d7e9f-e169-4d45-a131-a5ae444fae97.png">

**Expected result**
1. Fields should be properly aligned
2. <a href> should not be displayed in plain text but in HTML

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix
