### ISSUE TITLE
Argument section visible but not functional in a topic when Social mention is clicked

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#5]
**Specifications**

MacOS Chrome

**Problem**
When the user goes to a topic and clicks on social mentions, the argument section remains in current position but since the social mention section is positioned on top of it, the argument section is not functional (screenshot attached)

<img width="1439" alt="Screenshot 2023-02-22 at 00 12 01" src="https://user-images.githubusercontent.com/72747107/220471181-de6e606e-7fd4-4768-9bd3-dfdd77a86b2a.png">

**Expected result**
1. Argument section should be hidden when social mentions is clicked (as per current live environment UX)

**Comment by ilmartyrk** [comment]
@ssin1901 posted a fix
