### ISSUE TITLE
Language section shows Crowdin as an option 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe-new#6]
**Specifications**

MacOS Chrome

**Problem**

When the user clicks on languages, Crowdin is showed as an option (screenshot). Also there is a big space in the middle on the left (highlighted in screenshot)

<img width="1440" alt="Screenshot 2023-02-22 at 14 07 42" src="https://user-images.githubusercontent.com/72747107/220616120-1365a479-aef8-44ae-ac57-8af68cf77d3d.png">

**Expected result**

Crowdin should not be a language option and options should be aligned.

**Comment by ilmartyrk** [comment]
@ssin1901 actually having Crowdin in there itself isn't an issue as it is an options from our configuration, not sure if @oksks uses it in our testing or not, but it only comes from test configuration so it will not be in our live environment. But I am not sure why you have this gap in the languages list, it doesn't display it like that for me

**Comment by ssin1901** [comment]
@ilmartyrk in reference to this screenshot (attached) maybe the issue is because of Crowdin? 

<img width="1440" alt="Screenshot 2023-02-23 at 15 14 00" src="https://user-images.githubusercontent.com/72747107/220916916-b2d4eaf3-5c54-49a8-98a1-ae8ce2e68b8f.png">

**Comment by ilmartyrk** [comment]
@oksks should we keep it or not? I have no problem with it being there in testing.
